export { canDo, isAdmin } from './check.js'
export { PermissionDeniedError } from './errors.js'
export { grantPermission, revokePermission } from './grant.js'
export { userGroupsCTE, userGroupsSubquery } from './group-resolution.js'
export { registerEntityType } from './register-entity-type.js'
export type { UserContext, PermissionCheckResult } from './types.js'
export { visibleEntitiesSql, isAdminSql } from './visibility.js'
