#!/usr/bin/env bash
set -euo pipefail

cd /home/dev/workspace

BRANCH="${BRANCH:-$(git branch --show-current)}"
REVIEWERS="${REVIEWERS:-}"
PR_LABELS="${PR_LABELS:-ai-generated}"
SLACK_WEBHOOK_URL="${SLACK_WEBHOOK_URL:-}"

# ── Pre-flight checks ───────────────────────────────────────────────
echo "Running typecheck..."
if ! npm run typecheck; then
  echo "FAILED: typecheck — fix errors before submitting PR"
  exit 1
fi

echo "Running lint..."
if ! npm run lint; then
  echo "FAILED: lint — fix errors before submitting PR"
  exit 1
fi

# ── Check for changes ───────────────────────────────────────────────
if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  echo "No changes to commit."
  exit 0
fi

# ── Stage and commit ────────────────────────────────────────────────
git add -A
echo ""
echo "Changes to commit:"
git diff --cached --stat
echo ""

# Generate commit message from diff
DIFF_SUMMARY=$(git diff --cached --stat | tail -1)
read -r -p "Commit message (default: 'AI: ${DIFF_SUMMARY}'): " COMMIT_MSG
COMMIT_MSG="${COMMIT_MSG:-AI: ${DIFF_SUMMARY}}"

git commit -m "$COMMIT_MSG

Co-Authored-By: Claude <noreply@anthropic.com>"

# ── Push ─────────────────────────────────────────────────────────────
echo "Pushing to origin/${BRANCH}..."
git push -u origin "$BRANCH"

# ── Create PR ────────────────────────────────────────────────────────
echo "Creating pull request..."

PR_TITLE="${COMMIT_MSG}"
PR_BODY="## Summary

AI-generated changes on \`${BRANCH}\`.

## Checks
- [x] \`npm run typecheck\` passed
- [x] \`npm run lint\` passed

---
Generated by AI Developer Docker"

PR_CMD="gh pr create --title \"${PR_TITLE}\" --body \"$(cat <<'EOF'
${PR_BODY}
EOF
)\""

# Build gh pr create command
GH_ARGS=(gh pr create --title "$PR_TITLE" --body "$PR_BODY")

if [ -n "$REVIEWERS" ]; then
  GH_ARGS+=(--reviewer "$REVIEWERS")
fi

if [ -n "$PR_LABELS" ]; then
  # Create label if it doesn't exist (ignore errors)
  gh label create "$PR_LABELS" --description "Generated by AI Developer" --color "7057ff" 2>/dev/null || true
  GH_ARGS+=(--label "$PR_LABELS")
fi

PR_URL=$("${GH_ARGS[@]}" 2>&1)
echo ""
echo "PR created: $PR_URL"

# ── Slack notification ───────────────────────────────────────────────
if [ -n "$SLACK_WEBHOOK_URL" ]; then
  /home/dev/scripts/notify-slack.sh "pr-created" "PR created: $PR_URL"
fi

echo ""
echo "Done! PR is ready for review."
